export const mockComparisonData = [
  {
    id: "1",
    evcoPartNumber: "965313",
    clientPartNumber: "A12345",
    description: "Sensor de temperatura",
    previousForecast: 250,
    currentForecast: 291,
    changePercentage: 16.4,
    variationType: "normal",
    comments: "",
    client: "DONALDSON",
    period: "jun.25",
  },
  {
    id: "2",
    evcoPartNumber: "965328",
    clientPartNumber: "B67890",
    description: "Válvula de presión",
    previousForecast: 200,
    currentForecast: 250,
    changePercentage: 25,
    variationType: "moderada",
    comments: "Incremento por nueva línea de producción",
    client: "DONALDSON",
    period: "jul.25",
  },
  {
    id: "3",
    evcoPartNumber: "965327",
    clientPartNumber: "C13579",
    description: "Filtro de aire",
    previousForecast: 80,
    currentForecast: 100,
    changePercentage: 25,
    variationType: "moderada",
    comments: "",
    client: "DONALDSON",
    period: "jul.25",
  },
  {
    id: "4",
    evcoPartNumber: "965325",
    clientPartNumber: "D24680",
    description: "Sensor de presión",
    previousForecast: 320,
    currentForecast: 300,
    changePercentage: -6.25,
    variationType: "normal",
    comments: "Reducción por optimización de inventario",
    client: "DONALDSON",
    period: "jun.25",
  },
  {
    id: "5",
    evcoPartNumber: "965339",
    evcoNumber: "EV-5339",
    clientPartNumber: "E35791",
    description: "Conector eléctrico",
    previousForecast: 5000,
    currentForecast: 6000,
    changePercentage: 20,
    variationType: "moderada",
    comments: "",
    client: "DONALDSON",
    period: "jul.25",
  },
  {
    id: "6",
    evcoPartNumber: "965316",
    clientPartNumber: "F46802",
    description: "Soporte metálico",
    previousForecast: 100,
    currentForecast: 80,
    changePercentage: -20,
    variationType: "moderada",
    comments: "",
    client: "DONALDSON",
    period: "jun.25",
  },
  {
    id: "7",
    evcoPartNumber: "965337",
    clientPartNumber: "G57913",
    description: "Junta de goma",
    previousForecast: 750,
    currentForecast: 800,
    changePercentage: 6.67,
    variationType: "normal",
    comments: "",
    client: "DONALDSON",
    period: "jun.25",
  },
  {
    id: "8",
    evcoPartNumber: "965341",
    evcoNumber: "EV-5341",
    clientPartNumber: "H68024",
    description: "Tornillo especial",
    previousForecast: 50000,
    currentForecast: 57600,
    changePercentage: 15.2,
    variationType: "normal",
    comments: "Incremento por nuevo proyecto",
    isNew: false,
    client: "DONALDSON",
    period: "jun.25",
  },
  {
    id: "9",
    evcoPartNumber: "965331",
    clientPartNumber: "I79135",
    description: "Abrazadera metálica",
    previousForecast: 0,
    currentForecast: 1540,
    changePercentage: 100,
    variationType: "pico",
    comments: "Nuevo producto",
    isNew: true,
    client: "DONALDSON",
    period: "jul.25",
  },
  {
    id: "10",
    evcoPartNumber: "965307",
    clientPartNumber: "J80246",
    description: "Tubo de conexión",
    previousForecast: 1200,
    currentForecast: 1500,
    changePercentage: 25,
    variationType: "moderada",
    comments: "",
    client: "DONALDSON",
    period: "jul.25",
  },
]
